version: '3'
services:
  # SQL Server Docker Container
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dogadjaj123!
      - MSSQL_PID=Developer
    ports:
      - 1435:1433
    networks:
      - dogadjajnetwork

  # ASP.NET Core Application Docker Container
  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dogadjaj_ba\Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=Server=sql,1433;Database=dogadjajba;User=sa;Password=Dogadjaj123!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:80
    networks:
      - dogadjajnetwork
    links:
      - sql
    depends_on:
      - sql
networks:
  dogadjajnetwork:
    driver: bridge



